# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MilkTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('provider_rating', models.IntegerField(blank=True, null=True)),
                ('customer_rating', models.IntegerField(blank=True, null=True)),
                ('customer', models.ManyToManyField(related_name='customer', to='user.UserProfile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.Location')),
                ('provider', models.ManyToManyField(related_name='provider', to='user.UserProfile')),
            ],
        ),
    ]
