# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('post_date', models.DateField()),
                ('status', models.CharField(choices=[(b'available', b'Available'), (b'pending', b'Pending'), (b'cancelled', b'Cancelled')], default=b'available', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.Location')),
                ('provider', models.ManyToManyField(related_name='provider', to='user.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='milktransaction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='milktransaction',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='milktransaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='milktransaction',
            name='request_date',
        ),
        migrations.AddField(
            model_name='milktransaction',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='milk.MilkPost'),
            preserve_default=False,
        ),
    ]
