# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('milk', '0002_auto_20160723_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkpost',
            name='provider',
        ),
        migrations.AddField(
            model_name='milkpost',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='user.UserProfile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='milktransaction',
            name='customer',
        ),
        migrations.AddField(
            model_name='milktransaction',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='user.UserProfile'),
            preserve_default=False,
        ),
    ]
